/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Class.ConnectionDB;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

/**
 *
 * @author mamam
 */
public class login extends javax.swing.JFrame {      
    /**
     * Creates new form login
     */

      private javax.swing.JPanel Login;
    private javax.swing.JPanel Register;
    private javax.swing.JPanel Store;
    private javax.swing.JTextField emailRegister;
    private javax.swing.JTextField email;
    private javax.swing.JButton singIn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel side_pane;
    private javax.swing.JPanel home;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel cart;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel exit1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField nameRegister;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password2;
    private javax.swing.JPasswordField passwordRegister;
     private javax.swing.JLabel jLabel17;
    public login() {
          JOptionPane.showMessageDialog(null, "وهينا استخدمنا JOptionPane  علامة كاملة هيك , ههههه ");
         
String[] buttons = { "Log in", "Store"};         
       int returnValue = JOptionPane.showOptionDialog(null, "Choose one ", "Narrative",
        JOptionPane.WARNING_MESSAGE, 0, null, buttons, buttons);
        initComponents();
        
        this.setLocationRelativeTo(null);
        Register.hide();
        Store.hide();
         try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/store_project", "root","");
                Statement stat = conn.createStatement();
               ResultSet rs = stat.executeQuery("select * from admin");
            } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            }
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Store = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        side_pane = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cart = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        exit1 = new javax.swing.JLabel();
        nameRegister = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        passwordRegister = new javax.swing.JPasswordField();
        jTextField4 = new javax.swing.JTextField();
        singIn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        password2 = new javax.swing.JPasswordField();
        jTextField5 = new javax.swing.JTextField();
        emailRegister = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setDoubleBuffered(false);
        Login.setInheritsPopupMenu(true);
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/تعليق توضيحي 2019-05-18 175448.png"))); // NOI18N
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 460, 380));

        jLabel4.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(46, 47, 48));
        jLabel4.setText("LOGIN");
        Login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, 60));

        email.setBackground(new java.awt.Color(246, 246, 246));
        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setToolTipText("");
        email.setBorder(null);
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        Login.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 300, 50));

        password.setBackground(new java.awt.Color(246, 246, 246));
        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        Login.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 260, 50));

        jTextField2.setBackground(new java.awt.Color(246, 246, 246));
        jTextField2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jTextField2.setText("     Eamil : ");
        jTextField2.setToolTipText("");
        jTextField2.setBorder(null);
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        Login.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 400, 50));

        jTextField1.setBackground(new java.awt.Color(246, 246, 246));
        jTextField1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jTextField1.setText("     Password : ");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Login.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 400, 50));

        jLabel7.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel7.setText("Forgot Email / Password");
        Login.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 204, 0));
        jLabel8.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(133, 133, 133));
        jLabel8.setText("Create your Account");
        jLabel8.setToolTipText("");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel8.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        Login.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 160, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/تعليق توضيحي 2019-05-18 182952.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Login.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 310, 50));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit2.png"))); // NOI18N
        exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitMouseMoved(evt);
            }
        });
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        Login.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mamam\\Documents\\NetBeansProjects\\Store\\src\\Image\\borderForFrame.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setToolTipText("");
        Login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        Store.setBackground(new java.awt.Color(255, 255, 255));
        Store.setEnabled(false);
        Store.setFocusable(false);
        Store.setPreferredSize(new java.awt.Dimension(1000, 500));
        Store.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit2.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        Store.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/اطار المنتج.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 180));

        jLabel16.setToolTipText("");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 100, 80));

        Store.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 120, 180));

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(23, 35, 51));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Home");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, -1));

        cart.setBackground(new java.awt.Color(23, 35, 51));
        cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cartMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cart");
        jLabel12.setToolTipText("");

        javax.swing.GroupLayout cartLayout = new javax.swing.GroupLayout(cart);
        cart.setLayout(cartLayout);
        cartLayout.setHorizontalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cartLayout.setVerticalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(cartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, -1));

        profile.setBackground(new java.awt.Color(23, 35, 51));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profileMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Profile");

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel13)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(profileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, -1));

        logout.setBackground(new java.awt.Color(23, 35, 51));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logout");
        jLabel11.setToolTipText("");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(0, 44, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 120, -1));

        Store.add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 120, 490));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\mamam\\Documents\\NetBeansProjects\\Store\\src\\Image\\borderForFrame.png")); // NOI18N
        jLabel9.setText("jLabel2");
        jLabel9.setToolTipText("");
        jLabel9.setPreferredSize(new java.awt.Dimension(1000, 500));
        Store.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(Store, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        Register.setBackground(new java.awt.Color(255, 255, 255));
        Register.setEnabled(false);
        Register.setFocusable(false);
        Register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit2.png"))); // NOI18N
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });
        Register.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        nameRegister.setBackground(new java.awt.Color(246, 246, 246));
        nameRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameRegister.setToolTipText("");
        nameRegister.setBorder(null);
        nameRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRegisterActionPerformed(evt);
            }
        });
        Register.add(nameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 300, 50));

        jTextField3.setBackground(new java.awt.Color(246, 246, 246));
        jTextField3.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jTextField3.setText("     Name : ");
        jTextField3.setToolTipText("");
        jTextField3.setBorder(null);
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        Register.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 400, 50));

        passwordRegister.setBackground(new java.awt.Color(246, 246, 246));
        passwordRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordRegister.setBorder(null);
        passwordRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordRegisterActionPerformed(evt);
            }
        });
        Register.add(passwordRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 260, 50));

        jTextField4.setBackground(new java.awt.Color(246, 246, 246));
        jTextField4.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jTextField4.setText("     Password : ");
        jTextField4.setToolTipText("");
        jTextField4.setBorder(null);
        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        Register.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 400, 50));

        singIn.setBackground(new java.awt.Color(255, 255, 204));
        singIn.setIcon(new javax.swing.ImageIcon("C:\\Users\\mamam\\Desktop\\Singin.png")); // NOI18N
        singIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singInMouseClicked(evt);
            }
        });
        singIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singInActionPerformed(evt);
            }
        });
        Register.add(singIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 250, 50));

        jLabel5.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(46, 47, 48));
        jLabel5.setText("Register");
        Register.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 170, 60));

        password2.setBackground(new java.awt.Color(246, 246, 246));
        password2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password2.setBorder(null);
        password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password2ActionPerformed(evt);
            }
        });
        Register.add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 240, 50));

        jTextField5.setBackground(new java.awt.Color(246, 246, 246));
        jTextField5.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jTextField5.setText("   re-Password  : ");
        jTextField5.setToolTipText("");
        jTextField5.setBorder(null);
        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        Register.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 400, 50));

        emailRegister.setBackground(new java.awt.Color(246, 246, 246));
        emailRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailRegister.setToolTipText("");
        emailRegister.setBorder(null);
        emailRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailRegisterActionPerformed(evt);
            }
        });
        Register.add(emailRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 300, 50));

        jTextField6.setBackground(new java.awt.Color(246, 246, 246));
        jTextField6.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jTextField6.setText("     Eamil : ");
        jTextField6.setToolTipText("");
        jTextField6.setBorder(null);
        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        Register.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 400, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/backtoLogin.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        Register.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mamam\\Documents\\NetBeansProjects\\Store\\src\\Image\\borderForFrame.png")); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.setToolTipText("");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        Register.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));
        Register.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
           
    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed
    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_exitMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      try {
            Connection checkConnection = ConnectionDB.StoreDB();
            Class.forName("com.mysql.jdbc.Driver");
            try {
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/store_project", "root","");
               Statement stat = conn.createStatement();
               ResultSet rs = stat.executeQuery("select * from admin");
                while (rs.next()) {
                    String name = rs.getString("name");
                    String emailTest = rs.getString("email");
                
                    if(emailTest.equalsIgnoreCase(email.getText())){
                        if(rs.getString("password").equalsIgnoreCase(password.getText())){
                            System.out.println("login Success / user name : "+name);
                      
                           
                            
                    Store.show();
                    Login.hide();
                    Register.hide();
                    stat.execute("select * from admin");
                        }
                }
                }
              
            } catch (SQLException ex) {
            
            System.out.println(ex.getMessage());
            }
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
                    Store.hide();
                    Login.hide();
                    Register.show();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void emailRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailRegisterActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password2ActionPerformed

    private void singInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singInActionPerformed
        // TODO add your handling code here:

          try {
       String f = nameRegister.getText();String l = emailRegister.getText();String a = passwordRegister.getText();
         Date d = new Date();
            Connection conn = ConnectionDB.StoreDB();      
            Statement st = conn.createStatement();
            st.executeUpdate("CREATE TABLE IF NOT EXISTS `store_project`.`customers`"
                    + " ( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(20) "
                    + "NOT NULL , `email` VARCHAR(50) NOT NULL , "
                    + "`password` VARCHAR(20) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;");
            st.executeUpdate("CREATE TABLE IF NOT EXISTS `store_project`.`activities` "
                    + "( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(20) NOT NULL"
                    + " , `activitie` VARCHAR(50) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;");
              st.executeUpdate("INSERT INTO `customers` (`id`, `name`, `email`, `password`) VALUES (null,'"+f+"','"+l+"','"+a+"');");
                    st.executeUpdate("INSERT INTO `activities` (`id`, `name`, `activitie`) VALUES (NULL, '"+f+"', 'SingIn |"+d+"');");
            //ResultSet resultSet = st.executeQuery("select * from customers");
               
           /*
             while (resultSet.next()) {
                 if(resultSet.getString("email").equals(l)){
                 JOptionPane.showMessageDialog(null, "Email EXISTS");
                 break;
                 }else{
                   st.executeUpdate("INSERT INTO `customers` (`id`, `name`, `email`, `password`) VALUES (null,'"+f+"','"+l+"','"+a+"');");
                    st.executeUpdate("INSERT INTO `activities` (`id`, `name`, `activitie`) VALUES (NULL, '"+f+"', 'SingIn |"+d+"');");
                    conn.close();
                 }
                      }  */

         
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error"," in Databases",JOptionPane.ERROR_MESSAGE);
        }
        }
/*
    }//GEN-LAST:event_singInActionPerformed
*/
    private void singInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singInMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_singInMouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void passwordRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordRegisterActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void nameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRegisterActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nameRegisterActionPerformed

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_logoutMouseReleased

    private void profileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMousePressed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_profileMousePressed

    private void cartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_cartMousePressed

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_homeMousePressed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
                this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        // TODO add your handling code here:
                this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                this.dispose();
                
    }//GEN-LAST:event_exit1MouseClicked

    private void exitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseMoved
        // TODO add your handling code here:
                exit.setBackground(Color.red);

    }//GEN-LAST:event_exitMouseMoved

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
                            Login.show();
            
                     Store.hide();
                    Register.hide();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseClicked

    /**
     *  System.out.println("OK");
                Store.show();
                Login.hide();
                Register.hide();
     * @param args the command line arguments
     */
    public static void main(String args[]) { 
        //Connection to Databases
           try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/store_project", "root","");
                Statement stat = conn.createStatement();
               stat.executeUpdate("INSERT INTO customers (id , name , email , password ) VALUES (null ,'moaz','mama.moshtha','moaz'");
                   // +''nameRegister.getText()+''eamilRegister.getText()+','passwordRegister.getText());
            } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            }
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
           });
    }
}
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Register;
    private javax.swing.JPanel Store;
    private javax.swing.JPanel cart;
    private javax.swing.JTextField email;
    private javax.swing.JTextField emailRegister;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JPanel home;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel logout;
    private javax.swing.JTextField nameRegister;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password2;
    private javax.swing.JPasswordField passwordRegister;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel side_pane;
    private javax.swing.JButton singIn;
    // End of variables declaration//GEN-END:variables

*/